export default {
  '17896441': [() => import(/* webpackChunkName: '17896441' */ "@theme/DocItem"), "@theme/DocItem", require.resolveWeak("@theme/DocItem")],
  '1be78505': [() => import(/* webpackChunkName: '1be78505' */ "@theme/DocPage"), "@theme/DocPage", require.resolveWeak("@theme/DocPage")],
  '2a420b45': [() => import(/* webpackChunkName: '2a420b45' */ "@site/docs/examples/external.md"), "@site/docs/examples/external.md", require.resolveWeak("@site/docs/examples/external.md")],
  '3b8c55ea': [() => import(/* webpackChunkName: '3b8c55ea' */ "@site/docs/installation.md"), "@site/docs/installation.md", require.resolveWeak("@site/docs/installation.md")],
  '52630647': [() => import(/* webpackChunkName: '52630647' */ "@site/docs/workerstatus.md"), "@site/docs/workerstatus.md", require.resolveWeak("@site/docs/workerstatus.md")],
  '5e9f5e1a': [() => import(/* webpackChunkName: '5e9f5e1a' */ "@generated/docusaurus.config"), "@generated/docusaurus.config", require.resolveWeak("@generated/docusaurus.config")],
  '6476eba6': [() => import(/* webpackChunkName: '6476eba6' */ "@site/docs/usage.md"), "@site/docs/usage.md", require.resolveWeak("@site/docs/usage.md")],
  '66aefdcc': [() => import(/* webpackChunkName: '66aefdcc' */ "@site/docs/limitation.md"), "@site/docs/limitation.md", require.resolveWeak("@site/docs/limitation.md")],
  '8fa6841b': [() => import(/* webpackChunkName: '8fa6841b' */ "@site/docs/examples/sort.md"), "@site/docs/examples/sort.md", require.resolveWeak("@site/docs/examples/sort.md")],
  '935f2afb': [() => import(/* webpackChunkName: '935f2afb' */ "~docs/default/version-current-metadata-prop-751.json"), "~docs/default/version-current-metadata-prop-751.json", require.resolveWeak("~docs/default/version-current-metadata-prop-751.json")],
  'a09c2993': [() => import(/* webpackChunkName: 'a09c2993' */ "@site/docs/introduction.md"), "@site/docs/introduction.md", require.resolveWeak("@site/docs/introduction.md")],
  'a9152632': [() => import(/* webpackChunkName: 'a9152632' */ "@site/docs/useworker.md"), "@site/docs/useworker.md", require.resolveWeak("@site/docs/useworker.md")],
  'c4f5d8e4': [() => import(/* webpackChunkName: 'c4f5d8e4' */ "@site/src/pages/index.js"), "@site/src/pages/index.js", require.resolveWeak("@site/src/pages/index.js")],
  'd5669c0c': [() => import(/* webpackChunkName: 'd5669c0c' */ "@site/docs/examples/csv.md"), "@site/docs/examples/csv.md", require.resolveWeak("@site/docs/examples/csv.md")],};
